language: node_js

node_js: 
    - '10'

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "nejinn"
  - git config user.email "871966163@qq.com"
  - git add .
  - git commit -m "travis cl"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global: